language: node_js
node_js:
  - "9"
  - "8"
cache:
  directories:
    "node_modules"
before_script:
  - npm run clear
  - npm run build
  - npm run build:umd
  - npm rum build:umd:min
after_success:
  - npm run coveralls
